from .tenant import router as tenant
from .project import router as project
from .workflow import router as workflow
from .data_model import router as data_model
from .fields import router as fields
from .relationship import router as relationship
from .policy import router as policy
from .type_registry import router as type_registry
from .registries import router as registries
